{
 "title": "App Voting",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\", name=~\"worker|redis|database|backend|frontend\"}[1m])) by (name)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Unit Usage (Milicores)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",name=~\"worker|redis|database|backend|frontend\"}[1m]))by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Response duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"backend|frontend:3000|worker:3000\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Network In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", name=~\"backend|frontend|worker\"}[1m])) ",
     "legendFormat": "{{ name }} In"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", name=~\"backend|frontend|worker\"}[1m]))",
     "legendFormat": "{{ name }} Out"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total[5m])) by (method, status)",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  }
 ]
}